version: "2.1"
services:
  nginx:
    image: henahax/gw2-checklist:latest
    container_name: gw2-checklist
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8080:80
    restart: unless-stopped